apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-gateway-config
  labels:
    linkerd.io/control-plane-component: gateway
    linkerd.io/extension: multicluster
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.10.2
  namespace: linkerd-multicluster
data:
  nginx.conf: |-
    error_log stderr;
    pid /tmp/nginx.pid;
    events {
    }
    stream {
       server {
           listen     4180;
           proxy_pass 127.0.0.1:4140;
       }
    }
    http {
      client_body_temp_path /tmp/client_temp;
      proxy_temp_path       /tmp/proxy_temp_path;
      fastcgi_temp_path     /tmp/fastcgi_temp;
      uwsgi_temp_path       /tmp/uwsgi_temp;
      scgi_temp_path        /tmp/scgi_temp;
      server {
          listen     4181;
          location = /health {
            access_log off;
            return 200 "healthy\n";
          }

          location ~* ^/(.*)$ {
            deny all;
          }
      }
      server {
          listen     8888;
          location /health-local {
            access_log off;
            return 200 "healthy\n";
          }
      }
    }
