apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    linkerd.io/created-by: linkerd/cli stable-2.10.2
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: Linkerd
    app.kubernetes.io/version: stable-2.10.2
    linkerd.io/control-plane-component: gateway
    app: linkerd-gateway
    linkerd.io/extension: multicluster
  name: linkerd-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkerd-gateway
  template:
    metadata:
      annotations:
        linkerd.io/created-by: linkerd/cli stable-2.10.2
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-require-identity-inbound-ports: "4181,4143,4180"
        config.linkerd.io/enable-gateway: "true"
      labels:
        app: linkerd-gateway
    spec:
      volumes:
        - name: config
          configMap:
            name: linkerd-gateway-config
        - name: tmp
          emptyDir: {}
      containers:
        - name: nginx
          readinessProbe:
            failureThreshold: 7
            httpGet:
              path: /health-local
              port: 8888
          livenessProbe:
            httpGet:
              path: /health-local
              port: 8888
            initialDelaySeconds: 10
          image: nginx:1.17
          ports:
            - name: mc-relay
              containerPort: 4180
            - name: mc-probe
              containerPort: 4181
            - name: local-probe
              containerPort: 8888
          securityContext:
            runAsUser: 1001
          volumeMounts:
            - name: config
              mountPath: /etc/nginx
            - name: tmp
              mountPath: /tmp
      serviceAccountName: linkerd-gateway
