apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: hello
  annotations:
    configsync.gke.io/cluster-name-selector: select-env-prod
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
